/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `crypto' library (-lcrypto). */
#define HAVE_LIBCRYPTO 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "pppd-sql"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "mbroemme@plusserver.de"

/* Define to the full name of this package. */
#define PACKAGE_NAME "pppd-sql"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "pppd-sql 0.8.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "pppd-sql"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.8.0"

/* Plugin name as Prefix. */
#define PLUGIN_NAME_MYSQL "mysql"

/* Plugin name as Prefix. */
/* #undef PLUGIN_NAME_PGSQL */

/* Plugin version for MySQL. */
#define PLUGIN_VERSION_MYSQL "5.0.32"

/* Plugin version for PostgreSQL. */
/* #undef PLUGIN_VERSION_PGSQL */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.8.0"
